default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: trans_action_development

test:
  <<: *default
  database: trans_action_test

production:
  <<: *default
  database: trans_action_production
